# Generated by Django 3.2.5 on 2021-11-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogindetails',
            options={},
        ),
    ]
