# Generated by Django 3.2.5 on 2021-11-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userlogindetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogindetails',
            options={'ordering': ['created_at']},
        ),
    ]
