# Generated by Django 3.2.5 on 2021-11-12 05:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auto_20211112_1029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_backup_codes',
            unique_together={('user', 'backup_codes')},
        ),
    ]
