# Generated by Django 3.2.5 on 2021-11-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_backup_codes_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_BackUp_Codes',
        ),
    ]
